### ISSUE TITLE
The UI component doesn't contain support for SIMPLE Tasks

### ISSUE THREAD

**Issue by krishnaputhran** [FRINXio/frinx-workflow-ui#44]
I don't see a SIMPLE task component on the Workflow designer. As of now I see, support for only system tasks.

**Comment by marosmars** [comment]
Hey @krishnaputhran 

SIMPLE tasks should be listed in the left sidebar.
There are 2 buttons, one lists registered SIMPLE tasks and the other lists existing WORKFLOWS.
You can drag n drop an existing SIMPLE task or even existing workflows as a SUBWORKFLOW task. 

Note that it will only list tasks and workflows there if you have any task types registerd
