### ISSUE TITLE
HITTP Task component doesn't allow to change the name

### ISSUE THREAD

**Issue by krishnaputhran** [FRINXio/frinx-workflow-ui#46]
When you try to edit the HTTP task component, it doesn't allow to change the task name.

![image](https://user-images.githubusercontent.com/26684420/85919999-c304e980-b88d-11ea-88b2-4181cea68382.png)

**Comment by marosmars** [comment]
Hey @krishnaputhran 

I think that's intentional. Since we use SIMPLE task for HTTP(as discussed in the other issue you've opened) HTTP_task is the name of the SIMPLE task we use to invoke HTTP requests and if changed, it would not trigger the correct worker.

**Comment by tomasol** [comment]
maybe the UI should put more focus on reference names, as they are used, well, for referencing. They also don't have this limitation
